


export enum EventCategories {
    // Technology & Innovation
    TECH = "TECH",
    AI = "AI",
    SOFTWARE = "SOFTWARE",
    BLOCKCHAIN = "BLOCKCHAIN",
    CYBERSECURITY = "CYBERSECURITY",
    STARTUPS = "STARTUPS",
    HACKATHON = "HACKATHON",

    // Business & Finance
    BUSINESS = "BUSINESS",
    ENTREPRENEURSHIP = "ENTREPRENEURSHIP",
    MARKETING = "MARKETING",
    SALES = "SALES",
    FINANCE = "FINANCE",
    INVESTING = "INVESTING",
    ECONOMICS = "ECONOMICS",
    REAL_ESTATE = "REAL_ESTATE",

    // Education & Learning
    EDUCATION = "EDUCATION",
    WORKSHOP = "WORKSHOP",
    SEMINAR = "SEMINAR",
    TRAINING = "TRAINING",
    CERTIFICATION = "CERTIFICATION",
    BOOTCAMP = "BOOTCAMP",
    CAREER = "CAREER",

    // Arts, Media & Culture
    MUSIC = "MUSIC",
    CONCERT = "CONCERT",
    FESTIVAL = "FESTIVAL",
    ART = "ART",
    EXHIBITION = "EXHIBITION",
    FILM = "FILM",
    PHOTOGRAPHY = "PHOTOGRAPHY",
    FASHION = "FASHION",
    DESIGN = "DESIGN",
    THEATRE = "THEATRE",
    DANCE = "DANCE",

    // Sports & Fitness
    SPORTS = "SPORTS",
    FOOTBALL = "FOOTBALL",
    BASKETBALL = "BASKETBALL",
    TENNIS = "TENNIS",
    MARATHON = "MARATHON",
    FITNESS = "FITNESS",
    YOGA = "YOGA",
    GYM = "GYM",
    ESPORTS = "ESPORTS",

    // Health & Wellness
    HEALTH = "HEALTH",
    MENTAL_HEALTH = "MENTAL_HEALTH",
    WELLNESS = "WELLNESS",
    NUTRITION = "NUTRITION",
    MEDITATION = "MEDITATION",

    // Lifestyle & Social
    LIFESTYLE = "LIFESTYLE",
    NETWORKING = "NETWORKING",
    SOCIAL = "SOCIAL",
    DATING = "DATING",
    COMMUNITY = "COMMUNITY",
    VOLUNTEERING = "VOLUNTEERING",

    // Food & Drink
    FOOD = "FOOD",
    DRINKS = "DRINKS",
    COOKING = "COOKING",
    BAKING = "BAKING",
    WINE_TASTING = "WINE_TASTING",
    FOOD_FESTIVAL = "FOOD_FESTIVAL",

    // Travel & Outdoor
    TRAVEL = "TRAVEL",
    TOURISM = "TOURISM",
    ADVENTURE = "ADVENTURE",
    HIKING = "HIKING",
    CAMPING = "CAMPING",

    // Gaming & Entertainment
    GAMING = "GAMING",
    BOARD_GAMES = "BOARD_GAMES",
    CARD_GAMES = "CARD_GAMES",
    COSPLAY = "COSPLAY",
    COMEDY = "COMEDY",

    // Spiritual & Personal Growth
    SPIRITUAL = "SPIRITUAL",
    RELIGION = "RELIGION",
    PERSONAL_DEVELOPMENT = "PERSONAL_DEVELOPMENT",
    MOTIVATION = "MOTIVATION",
    MINDFULNESS = "MINDFULNESS",

    // Family & Kids
    FAMILY = "FAMILY",
    KIDS = "KIDS",
    PARENTING = "PARENTING",
    EDUCATIONAL_KIDS = "EDUCATIONAL_KIDS",

    // Environment & Sustainability
    ENVIRONMENT = "ENVIRONMENT",
    SUSTAINABILITY = "SUSTAINABILITY",
    CLIMATE = "CLIMATE",
    ECO_FRIENDLY = "ECO_FRIENDLY",

    // Government & Politics
    GOVERNMENT = "GOVERNMENT",
    POLITICS = "POLITICS",
    CIVIC = "CIVIC",

    // Other / Misc
    CHARITY = "CHARITY",
    FUNDRAISING = "FUNDRAISING",
    NON_PROFIT = "NON_PROFIT",
    OTHER = "OTHER",
}


export const formattedEventCategories = Object.values(EventCategories).map(
    (category) => ({
        value: category,
        label: category
            .replaceAll("_", " ")
            .toLowerCase()
            .replace(/\b\w/g, (l) => l.toUpperCase())
    })
);


const events = [
    {
        "id": 7,
        "creatorId": 18,
        "title": "Accra Startup Connect 2025",
        "desc": "A networking event for founders and investors.",
        "location": "Kempinski Hotel Gold Coast City, Accra",
        "capacity": 200,
        "ticket_price": 50,
        "category": "BUSINESS",
        "start_date": "2025-11-15T09:00:00.000Z",
        "end_date": "2025-11-15T18:00:00.000Z",
        "images": null,
        "ticketsSold": 0,
        "is_approved": false,
        "feature_event": false,
        "deleted": false,
        "created_at": "2025-10-01T12:00:00.000Z",
        "updated_at": "2025-10-01T12:00:00.000Z"
    },
    {
        "id": 8,
        "creatorId": 12,
        "title": "AI & Robotics Summit Ghana",
        "desc": "Exploring the future of AI and robotics in Africa.",
        "location": "Accra International Conference Centre",
        "capacity": 300,
        "ticket_price": 100,
        "category": "TECH",
        "start_date": "2025-10-05T08:00:00.000Z",
        "end_date": "2025-10-06T17:00:00.000Z",
        "images": null,
        "ticketsSold": 0,
        "is_approved": false,
        "feature_event": true,
        "deleted": false,
        "created_at": "2025-09-01T10:00:00.000Z",
        "updated_at": "2025-09-01T10:00:00.000Z"
    },
    {
        "id": 9,
        "creatorId": 21,
        "title": "Ghana Music & Culture Festival",
        "desc": "Celebrating Ghanaian music, dance, and culture.",
        "location": "Independence Square, Accra",
        "capacity": 5000,
        "ticket_price": 20,
        "category": "ENTERTAINMENT",
        "start_date": "2025-12-10T15:00:00.000Z",
        "end_date": "2025-12-12T23:00:00.000Z",
        "images": null,
        "ticketsSold": 0,
        "is_approved": true,
        "feature_event": true,
        "deleted": false,
        "created_at": "2025-08-20T09:30:00.000Z",
        "updated_at": "2025-08-20T09:30:00.000Z"
    },
    {
        "id": 10,
        "creatorId": 16,
        "title": "University of Ghana Tech Expo",
        "desc": "Showcasing student innovations and projects.",
        "location": "University of Ghana, Legon",
        "capacity": 800,
        "ticket_price": 0,
        "category": "TECH",
        "start_date": "2025-09-20T09:00:00.000Z",
        "end_date": "2025-09-20T17:00:00.000Z",
        "images": null,
        "ticketsSold": 0,
        "is_approved": true,
        "feature_event": false,
        "deleted": false,
        "created_at": "2025-08-01T11:00:00.000Z",
        "updated_at": "2025-08-01T11:00:00.000Z"
    },
    {
        "id": 11,
        "creatorId": 14,
        "title": "Digital Marketing Bootcamp Accra",
        "desc": "Learn modern digital marketing strategies.",
        "location": "Impact Hub Accra",
        "capacity": 120,
        "ticket_price": 75,
        "category": "EDUCATION",
        "start_date": "2025-11-01T09:00:00.000Z",
        "end_date": "2025-11-03T16:00:00.000Z",
        "images": null,
        "ticketsSold": 0,
        "is_approved": false,
        "feature_event": false,
        "deleted": false,
        "created_at": "2025-09-10T08:00:00.000Z",
        "updated_at": "2025-09-10T08:00:00.000Z"
    },
    {
        "id": 12,
        "creatorId": 25,
        "title": "Health & Wellness Fair Ghana",
        "desc": "Free health screenings and wellness talks.",
        "location": "Efua Sutherland Children's Park, Accra",
        "capacity": 1000,
        "ticket_price": 0,
        "category": "HEALTH",
        "start_date": "2025-08-25T08:00:00.000Z",
        "end_date": "2025-08-25T18:00:00.000Z",
        "images": null,
        "ticketsSold": 0,
        "is_approved": true,
        "feature_event": false,
        "deleted": false,
        "created_at": "2025-07-15T10:00:00.000Z",
        "updated_at": "2025-07-15T10:00:00.000Z"
    },
    {
        "id": 13,
        "creatorId": 19,
        "title": "CodeFest Ghana 2025",
        "desc": "Hackathon and developer conference.",
        "location": "AITI-KACE, Accra",
        "capacity": 250,
        "ticket_price": 30,
        "category": "TECH",
        "start_date": "2025-10-18T08:00:00.000Z",
        "end_date": "2025-10-19T20:00:00.000Z",
        "images": null,
        "ticketsSold": 0,
        "is_approved": false,
        "feature_event": false,
        "deleted": false,
        "created_at": "2025-09-05T12:00:00.000Z",
        "updated_at": "2025-09-05T12:00:00.000Z"
    },
    {
        "id": 14,
        "creatorId": 30,
        "title": "Women in Tech Ghana Summit",
        "desc": "Empowering women in technology fields.",
        "location": "Labadi Beach Hotel, Accra",
        "capacity": 400,
        "ticket_price": 60,
        "category": "TECH",
        "start_date": "2025-11-22T09:00:00.000Z",
        "end_date": "2025-11-22T17:00:00.000Z",
        "images": null,
        "ticketsSold": 0,
        "is_approved": true,
        "feature_event": true,
        "deleted": false,
        "created_at": "2025-09-12T09:00:00.000Z",
        "updated_at": "2025-09-12T09:00:00.000Z"
    },
    {
        "id": 15,
        "creatorId": 11,
        "title": "Accra Food & Drinks Festival",
        "desc": "Taste dishes from top chefs across Ghana.",
        "location": "Efua Sutherland Park, Accra",
        "capacity": 1500,
        "ticket_price": 25,
        "category": "LIFESTYLE",
        "start_date": "2025-12-05T12:00:00.000Z",
        "end_date": "2025-12-06T23:00:00.000Z",
        "images": null,
        "ticketsSold": 0,
        "is_approved": true,
        "feature_event": false,
        "deleted": false,
        "created_at": "2025-08-28T13:00:00.000Z",
        "updated_at": "2025-08-28T13:00:00.000Z"
    },
    {
        "id": 16,
        "creatorId": 22,
        "title": "Blockchain & Web3 Conference Ghana",
        "desc": "Exploring blockchain adoption in Africa.",
        "location": "Marriott Hotel, Accra",
        "capacity": 350,
        "ticket_price": 120,
        "category": "TECH",
        "start_date": "2025-10-30T09:00:00.000Z",
        "end_date": "2025-10-31T18:00:00.000Z",
        "images": null,
        "ticketsSold": 0,
        "is_approved": false,
        "feature_event": false,
        "deleted": false,
        "created_at": "2025-09-18T10:00:00.000Z",
        "updated_at": "2025-09-18T10:00:00.000Z"
    },
    {
        "id": 17,
        "creatorId": 27,
        "title": "Youth Leadership Summit Ghana",
        "desc": "Building the next generation of leaders.",
        "location": "British Council Hall, Accra",
        "capacity": 600,
        "ticket_price": 15,
        "category": "EDUCATION",
        "start_date": "2025-09-10T08:00:00.000Z",
        "end_date": "2025-09-10T17:00:00.000Z",
        "images": null,
        "ticketsSold": 0,
        "is_approved": true,
        "feature_event": false,
        "deleted": false,
        "created_at": "2025-08-05T09:00:00.000Z",
        "updated_at": "2025-08-05T09:00:00.000Z"
    },
    {
        "id": 18,
        "creatorId": 20,
        "title": "Fintech Innovation Forum Accra",
        "desc": "Discussing the future of digital finance.",
        "location": "World Trade Center, Accra",
        "capacity": 280,
        "ticket_price": 80,
        "category": "FINANCE",
        "start_date": "2025-11-12T09:00:00.000Z",
        "end_date": "2025-11-12T17:00:00.000Z",
        "images": null,
        "ticketsSold": 0,
        "is_approved": false,
        "feature_event": false,
        "deleted": false,
        "created_at": "2025-09-02T10:00:00.000Z",
        "updated_at": "2025-09-02T10:00:00.000Z"
    },
    {
        "id": 19,
        "creatorId": 24,
        "title": "Photography & Creative Arts Expo",
        "desc": "Showcasing creative talents in photography and design.",
        "location": "Alliance Française, Accra",
        "capacity": 500,
        "ticket_price": 10,
        "category": "ART",
        "start_date": "2025-10-12T10:00:00.000Z",
        "end_date": "2025-10-13T18:00:00.000Z",
        "images": null,
        "ticketsSold": 0,
        "is_approved": true,
        "feature_event": false,
        "deleted": false,
        "created_at": "2025-08-18T11:00:00.000Z",
        "updated_at": "2025-08-18T11:00:00.000Z"
    },
    {
        "id": 20,
        "creatorId": 28,
        "title": "Green Energy & Climate Summit Ghana",
        "desc": "Discussions on renewable energy and sustainability.",
        "location": "Accra Marriott Hotel",
        "capacity": 320,
        "ticket_price": 40,
        "category": "ENVIRONMENT",
        "start_date": "2025-12-18T09:00:00.000Z",
        "end_date": "2025-12-18T17:00:00.000Z",
        "images": null,
        "ticketsSold": 0,
        "is_approved": true,
        "feature_event": true,
        "deleted": false,
        "created_at": "2025-09-25T10:00:00.000Z",
        "updated_at": "2025-09-25T10:00:00.000Z"
    }
]
